version: '3.8'
services:
  applications:
    image: vikrant1020/celery
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - redis 
    networks:
      - Connect                      

  redis:
    image: redis:alpine
    networks:
      - Connect
    ports:
      - 6379:6379

  celery:
    image: vikrant1020/celery
    command: celery -A cleary.celery worker -l info -P gevent
    depends_on:
      - redis
      - applications
    networks:
      - Connect

  celery-beat:
    image: vikrant1020/celery
    command: celery -A cleary.celery beat -l info

    depends_on:
      - redis
      - applications
    networks:
      - Connect

networks:
  Connect:
