version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis 
    networks:
      - Connect                      

  redis:
    image: redis:alpine
    networks:
      - Connect
    ports:
      - 6379:6379

  celery:
    build: .
    command: celery -A cleary.celery worker -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
    networks:
      - Connect

  celery-beat:
    build: .
    command: celery -A cleary.celery beat -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis

networks:
  Connect:
    # driver: 